# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Warcraft Recorder CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.0'
        cache: 'npm'
    - run: npm install
    - run: npm run package
    - name: run unit tests 
      run: npm test
    - run: mv ./release/build/WarcraftRecorder*.exe ./release/build/WarcraftRecorder-$env:GITHUB_RUN_ID.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WarcraftRecorder
        path: release/build/WarcraftRecorder*.exe
